name: Security Audit

on:
  push:
    branches: [main, "dev/*"]
  pull_request:
    branches: [main, "dev/*"]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  security:
    uses: brig-id/.github/.github/workflows/security-audit-web.yml@6fe7dcf9ebe5a5f0d0439bef978f68c27b07cbc3 # main @ 2026-09-03
    with:
      working-directory: .
    secrets:
      WEBAWESOME_NPM_TOKEN: ${{ secrets.WEBAWESOME_NPM_TOKEN }}
